---
title: "cross-validation setting"
author: "Eguchi"
date: "2018/9/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse"); library("DataExplorer")
```

```{r}
base_train <- read_csv("base_train.csv")
base_test <- read_csv("base_test.csv")

train_device <- read_csv("train_device.csv")
test_device <- read_csv("test_device.csv")

train_geoNetwork <- read_csv("train_geoNetwork.csv")
test_geoNetwork <- read_csv("test_geoNetwork.csv")

train_trafficSource <- read_csv("train_trafficSource.csv")
test_trafficSource <- read_csv("test_trafficSource.csv")

train_totals <- read_csv("totals.csv")
test_totals <- read_csv("totals_test.csv")

dftrain <- data.frame(base_train, train_device, train_geoNetwork, train_trafficSource, train_totals)
dftest <- data.frame(base_test, test_device, test_geoNetwork, test_trafficSource, test_totals)

rm(base_train, train_device, train_geoNetwork, train_trafficSource, train_totals, 
   base_test, test_device, test_geoNetwork, test_trafficSource, test_totals); gc(); gc()
```

```{r}
dftrain$transactionRevenue2 <- dftrain$transactionRevenue
dftrain$transactionRevenue2[is.na(dftrain$transactionRevenue2)] <- 0
dftrain$transactionRevenue2[dftrain$transactionRevenue2 > 0.001] <- 1
```

```{r}
dftrain$transactionRevenue[is.na(dftrain$transactionRevenue)] <- 1
```

```{r}
dftrain$adwordsClickInfo.criteriaParameters <- NULL
dftest$adwordsClickInfo.criteriaParameters <- NULL
```

```{r}
dftrain <- dftrain[order(as.Date(dftrain$date, format="%Y/%m/%d")),]
```

```{r}
temp_daycount <- as.data.frame(table(dftrain$date))
```

## time-series CV設定
```{r}
dftrainCV1 <- dftrain[1:sum(temp_daycount$Freq[1:107]), ]
dftrainCV2 <- dftrain[1: sum(temp_daycount$Freq[1:155]), ]
dftrainCV3 <- dftrain[1: sum(temp_daycount$Freq[1:207]), ]
dftrainCV4 <- dftrain[1: sum(temp_daycount$Freq[1:256]), ]
dftrainCV5 <- dftrain[1: sum(temp_daycount$Freq[1:307]), ]

dftrainRes1 <- dftrain[sum(temp_daycount$Freq[1:121]+1): sum(temp_daycount$Freq[1:171]), ]
dftrainRes2 <- dftrain[sum(temp_daycount$Freq[1:172]+1): sum(temp_daycount$Freq[1:220]), ]
dftrainRes3 <- dftrain[sum(temp_daycount$Freq[1:221]+1): sum(temp_daycount$Freq[1:269]), ]
dftrainRes4 <- dftrain[sum(temp_daycount$Freq[1:270]+1): sum(temp_daycount$Freq[1:320]), ]
dftrainRes5 <- dftrain[sum(temp_daycount$Freq[1:321]+1): sum(temp_daycount$Freq[1:366]), ]
```

とてもエレガントとは言えんがまあいいや…
きれいな書き方あれば希望。

```{r}
write_csv(dftrainCV1, "dftrainCV1.csv")
write_csv(dftrainCV2, "dftrainCV2.csv")
write_csv(dftrainCV3, "dftrainCV3.csv")
write_csv(dftrainCV4, "dftrainCV4.csv")
write_csv(dftrainCV5, "dftrainCV5.csv")

write_csv(dftrainRes1, "dftrainRes1.csv")
write_csv(dftrainRes2, "dftrainRes2.csv")
write_csv(dftrainRes3, "dftrainRes3.csv")
write_csv(dftrainRes4, "dftrainRes4.csv")
write_csv(dftrainRes5, "dftrainRes5.csv")
write_csv(dftest, "dftest.csv")
```















f